config/routes.rb
Rails.application.routes.draw do
  root to: 'choices#index'
  resources :choices do
    resources :comments
  end
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  has_many :comments
  validates :option, presence: true
  validates :option_a, presence: true
  validates :option_b, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :choice
  validates :text, presence: true
  validates :choice_id, presence: true
  default_scope { order('created_at DESC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :set_choice, only: [:show, :edit, :update, :destroy]

  # GET /choices
  # GET /choices.json
  def index
    @new_comment = Comment.new
    @choices = Choice.all
  end

  # GET /choices/1
  # GET /choices/1.json
  def show
    @new_comment = Comment.new
  end

  # GET /choices/new
  def new
    @choice = Choice.new
  end

  # GET /choices/1/edit
  def edit
  end

  # POST /choices
  # POST /choices.json
  def create
    @choice = Choice.new(choice_params)

    respond_to do |format|
      if @choice.save
        format.html { redirect_to @choice, notice: 'Choice was successfully created.' }
        format.json { render :show, status: :created, location: @choice }
        format.js
      else
        format.html { render :new }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /choices/1
  # PATCH/PUT /choices/1.json
  def update

    params[:choice][:option_a_votes] = @choice.option_a_votes + params[:choice][:option_a_votes].to_i
    params[:choice][:option_b_votes] = @choice.option_b_votes + params[:choice][:option_b_votes].to_i

    respond_to do |format|
      if @choice.update(choice_params)
        format.html { redirect_to @choice, notice: 'Choice was successfully updated.' }
        format.json { render :show, status: :ok, location: @choice }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.json
  def destroy
    @choice.destroy
    respond_to do |format|
      format.html { redirect_to choices_url, notice: 'Choice was successfully destroyed.' }
      format.json { head :no_content }
      format.js { redirect_to choices_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choice
      @choice = Choice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def choice_params
      params.require(:choice).permit(:option, :option_a, :option_b, :option_a_image, :option_b_image, :option_a_votes, :option_b_votes)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_choice, only: [:show, :create]

  def create
    @comment = @choice.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to choices_path, notice: 'Comment was successfully created.' }
        format.js
      else
        format.html { redirect_to choices_path, notice: 'Comment creation failed.' }
        format.js
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_choice
    @choice = Choice.find(params[:choice_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def human_date(artime)
    t = artime.to_time
    return t.localtime.strftime("%b. %d")
  end

  def human_time(artime)
    t = artime.to_time
    return t.localtime.strftime("%I:%M %p")
  end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/choices/_choice.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= choice.option %>...</h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-3 col-sm-5 thumb">
    <a id="a" data-id="<%= choice.id %>" class="thumbnail" href='javascript:void(0)'>
      <img class="img-responsive" src="<%= choice.option_a_image %>" alt="">
      <span>A: <%= choice.option_a %></span>
    </a>
  </div>

  <div class="col-lg-2 col-sm-2">
    <div id="vote-display-<%= choice.id %>">
      <h1 id="or">OR</h1>
    </div>
  </div>

  <div class="col-lg-3 col-sm-5 thumb">
    <a id="b" data-id="<%= choice.id %>" class="thumbnail" href='javascript:void(0)' >
      <img class="img-responsive" src="<%= choice.option_b_image %>" alt="">
      <span>B: <%= choice.option_b %></span>
    </a>
  </div>

  <div class="col-lg-4 col-sm-12">
    <%= form_for([choice, @new_comment], remote: true) do |f| %>
      <div class="row">
        <div class="input-group comment-control">
          <%= f.label :text, style: "visibility: hidden;" %><br>
          <%= f.text_field :text, class: "form-control" %>
          <span class="input-group-btn">
            <%= f.submit "Comment", class: "btn btn-default" %>
          </span>
        </div>
      </div>
    <% end %>

    <div class="comments-display" id="comments-display-for-choice-<%= choice.id %>">
      <%= render choice.comments %>
    </div>
  </div>

</div>
<div class="row hidden-form" data-id="<%= choice.id %>">

  <%= form_for(choice, remote: true) do |f| %>
  <%= f.text_field :option_a_votes, value: 0 %>
  <%= f.text_field :option_b_votes, value: 0 %>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

  <%= link_to 'Edit', edit_choice_path(choice) %> |
  <%= link_to 'Back', choices_path %>

</div>

app/views/choices/_form.html.erb
<% if @choice.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@choice.errors.count, "error") %> prohibited this choice from being saved:</h2>
    <ul>
    <% @choice.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
      <%= form_for(@choice) do |f| %>
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <div class="field">
            <%= f.label :option %><br>
            <%= f.text_field :option %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 col-md-offset-2">
          <div class="field">
            <%= f.label :option_a %><br>
            <%= f.text_field :option_a %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="field">
            <%= f.label :option_a_image %><br>
            <%= f.text_field :option_a_image %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 col-md-offset-2">
          <div class="field">
            <%= f.label :option_b %><br>
            <%= f.text_field :option_b %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="field">
            <%= f.label :option_b_image %><br>
            <%= f.text_field :option_b_image %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <div class="actions">
            <%= f.submit %>
          </div>
        </div>
      </div>
      <% end %>
</div>

app/views/choices/_votes.html.erb
<%= column_chart [
  ["A", @choice.option_a_votes],
  ["B", @choice.option_b_votes]
], id: "vote-chart-#{@choice.id}" %>
<h5>Total Votes: <%= @choice.option_a_votes + @choice.option_b_votes %></h5>

app/views/choices/edit.html.erb
<h1>Editing Choice</h1>

<%= render 'form' %>

<%= link_to 'Show', @choice %> |
<%= link_to 'Back', choices_path %>

app/views/choices/index.html.erb
<div class="container">
  <%= render @choices %>
</div>

app/views/choices/new.html.erb
<h1>New Choice</h1>

<%= render 'form' %>

<%= link_to 'Back', choices_path %>

app/views/choices/show.html.erb
<div class="container">
  <%= render @choice %>
</div>

<% content_for :nav_menu do %>
  <li><%= link_to 'Edit this Choice', edit_choice_path(@choice) %></li>
  <li><%= link_to 'Delete this Choice', @choice, method: :delete, data: { confirm: 'Are you sure?' } %></li>
<% end %>

app/views/choices/update.js.erb
console.log("choices/update.js.erb");

$("form input:text[name='choice[option_a_votes]']").val("0");
$("form input:text[name='choice[option_b_votes]']").val("0");
var renderDiv = "#vote-display-" + "<%= @choice.id %>";
console.log("render votes display to div with id: " + renderDiv)
$(renderDiv).html("<%= j (render 'votes', choice: @choice) %>");

app/views/comments/_comment.html.erb
<div class="display-comment">
  <p>
    <span class="shrink-and-fade">@<%= human_time(comment.created_at) %></span>: <%= comment.text %>
  </p>
</div>

app/views/comments/create.js.erb
console.log("comments/create.js.erb");

var reloadCommentsDivID = "#comments-display-for-choice-" + "<%= @choice.id %>";

<% if @comment.errors.count == 0 %>
  $(reloadCommentsDivID).html("<%= j (render @choice.comments) %>");
  $("input[type='text'][name='comment[text]']").val("");
<% else %>
  $(reloadCommentsDivID).prepend("<div class='error'>error - you have to provide a value</div>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WouldYouRather</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <strong class="logo">
          <a href="/">would you rather</a>
        </strong>

        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Add New Choice', new_choice_path %></li>
              <%= yield :nav_menu %>
            </ul>
          </li>
        </ul>

      </div>
    </div>
  </div>

  <%= yield %>

</body>
</html>